# Generated by Django 2.0 on 2019-01-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duowan',
            name='style',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hupu',
            name='style',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='xinlang',
            name='style',
            field=models.CharField(default='其他', max_length=50),
        ),
    ]
