# Generated by Django 2.0 on 2019-01-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0003_auto_20190101_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='duowan',
            name='home_url',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hupu',
            name='home_url',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='xinlang',
            name='home_url',
            field=models.CharField(default='', max_length=50),
        ),
    ]
